apiVersion: v1
kind: Service
metadata:
  name: ai-service
  namespace: sentinelai
  labels:
    app: ai-service
spec:
  ports:
  - port: 8000
    targetPort: 8000
  selector:
    app: ai-service
  type: ClusterIP
